KVM-VMI/kvm-vmi

- README.md
> README: add presentations

- README.md
- vagrant/ansible/roles/vm/files/templates/win7.json
- vagrant/ansible/roles/vm/tasks/build.yml
Add presentations related to KVMi, and add small fixes on playbook
> Add presentations

- vagrant/ansible/roles/kvm/tasks/libkvmi.yml
use https://github.com/KVM-VMI/kvm/pull/30
> vagrant: install libkvmi with make install rule

- vagrant/ansible/roles/kvm/tasks/libkvmi.yml
use new https://github.com/bitdefender/libkvmi repo
> ansible: use libkvmi repo

- vagrant/ansible/playbook_1.yml
- vagrant/ansible/roles/kvm/tasks/install_deb.yml
- vagrant/ansible/roles/kvm/tasks/install_normal.yml
- vagrant/ansible/roles/kvm/tasks/main.yml
- vagrant/ansible/roles/vm/tasks/main.yml
add variable `kvm_install_package` to control how KVM should be installed.
- make deb-pkg
or
- sudo make install
defaults to the latter
> ansible: add kvm_install_package var to toggle make deb-pkg for kvm

- .github/workflows/doc.yml
- README.md
fix https://github.com/KVM-VMI/kvm-vmi/issues/72
> actions: build doc for multiple versions of KVMi

- docs/setup.md
libkvmi branch should be `master`
> docs: fix libkvmi branch

- docs/kvmi.md
add documentation for kvmi v2 and v3
> docs: add documentation for kvmi v2 and v3

- .travis.yml
- README.md
- vagrant/Vagrantfile
- vagrant/ansible/playbook_2.yml
- vagrant/ansible/roles/vm/tasks/build.yml
- vagrant/ansible/roles/vm/tasks/download.yml
- vagrant/ansible/roles/vm/tasks/main.yml
- vagrant/ansible/roles/vm/tasks/setup.yml
- vagrant/ansible/roles/vm/templates/domain-template.xml.j2
add build test for Vagrant on Travis CI
> travis: add build for vagrant

- .travis.yml
- vagrant/Vagrantfile
- vagrant/ansible/playbook_2.yml
- vagrant/ansible/roles/kvm/tasks/main.yml
Update KVMI-v7 with the latest patches on QEMU and KVM
- https://github.com/KVM-VMI/kvm/pull/44
- https://github.com/KVM-VMI/qemu/pull/7
> Update kvmi v7

- .gitmodules
- docs/overview.md
- docs/setup.md
- vagrant/Vagrantfile
- vagrant/ansible/roles/kvm/tasks/libkvmi.yml
> Add libkvmi submodule

- vagrant/Vagrantfile
> vagrant: bump box to v3.2.18

- vagrant/Vagrantfile
> vagrant: bump box to v3.3.2

- .travis.yml
* dist: bionic :arrow_right: focal
* vagrant: v2.2.14 :arrow_right: v2.2.18
> CI: bump dist and vagrant

- docs/kvmi.md
Add info about v11 and v12 kernel patch series.
> docs: add info about v11 and v12

- vagrant/Vagrantfile
Bump to v4.2.8 after comment https://github.com/KVM-VMI/kvm-vmi/commit/744e74e7490a26548fb48dbc1937c4c00ccf5753#commitcomment-95310173
> vagrant: bump box to v4.2.8

- .github/workflows/build.yml
- docs/setup.md
> ci: add build workflow to test kvm on multiple Ubuntu releases

- .github/workflows/doc.yml
> ci/doc: bump python

- .github/workflows/doc.yml
> ci/doc: fix python 3.10 string

- docs/setup.md
> docs: fix broken link to HVMI blog

- vagrant/Vagrantfile
> vagrant: update box to fix grub-pc dpkg issue

- vagrant/Vagrantfile
> vagrant: update apt cache before installing Ansible
